#!/bin/bash

set -e

echo ''
echo 'Check JavaScript Linting'
jslint ./immunity_ipam/static/immunity-ipam/js/*.js

echo ''
echo 'Check CSS Linting'
stylelint ./immunity_ipam/static/immunity-ipam/css/*.css

echo ''
echo 'Running checks for immunity_ipam'

immunity-qa-check \
          --migration-path ./immunity_ipam/migrations/ \
          --migration-module immunity_ipam

echo ''
echo 'Running checks for SAMPLE_APP'

SAMPLE_APP=1 immunity-qa-check \
              --skip-isort \
              --skip-flake8 \
              --skip-checkmigrations \
              --skip-checkendline \
              --skip-checkcommit \
              --migration-path "./tests/immunity2/sample_ipam/migrations
                                ./tests/immunity2/sample_users/migrations"

